### ISSUE TITLE
Dip switches no. of lives

### ISSUE THREAD

**Issue by bnice** [antongale/EXERION#2]
Hi,
Just playing your excellent Exerion and found a small bug. When you are in dip switches and settings the number of lives it 1,2,3,4,5a,5b,5c,free. I guess 5a, 5b, 5c should be something else?

Ben.

**Comment by antongale** [comment]
This is the way the original board is.  It has 3 dip switch selections where 5 lives are given.  You have to differentiate between 5 distinct names in the MiSTer menu otherwise I couldn't put the free-play in at the end.  So, its not a bug, just an oddity.

**Comment by bnice** [comment]
👍 Cool, wouldn't of guessed that.
